"""Acceptance test for the complete project generated by ``viper init``."""

from __future__ import annotations

import hashlib
import os
import sys
from collections.abc import Mapping
from pathlib import Path

from tests.fixtures import (
    builtin_http,
    http_policy,
    http_request,
    python_environment,
    reproducibility,
)
from tests.git_repository import REPOSITORY, run_git
from tests.test_run_execution import http_source as execution_http_source
from viper import _subprocess as subprocess
from viper import parameters
from viper._schema import (
    PARAMETERS,
    PREDICTIONS,
    RESUME_STATE,
    DataRole,
)
from viper.artifacts import (
    ArtifactLoaderRef,
    ArtifactPointer,
    SingleFileArtifactSpec,
    StageArtifactRef,
)
from viper.authoring import (
    RunPlanDraft,
    StageDraft,
    freeze_run_plan,
    write_benchmark_spec,
    write_experiment_spec,
    write_variant_spec,
)
from viper.benchmark import (
    BenchmarkResult,
    BenchmarkSpec,
    MetricCriterion,
)
from viper.experiments import (
    BuildVariantStageParams,
    EmbedVariantStageParams,
    EvaluateVariantStageParams,
    ExperimentSpec,
    ReplicateSpec,
    TrainVariantStageParams,
    VariantSpec,
)
from viper.inputs import FutureInputRef, StoredInputRef
from viper.metrics import (
    FloatComparator,
    MetricDependency,
    MetricImplementationRef,
    MetricSpec,
)
from viper.parameters import ParameterModelRef
from viper.project import init
from viper.references import (
    ArtifactPointerRef,
    GitFileRef,
    GitSource,
    ResolvedRunRef,
)
from viper.runs import ResolvedRun
from viper.runtime import (
    CPUComputeSpec,
    GCEEnvironmentSpec,
    LocalEnvironmentSpec,
    observe_gce_provisioning,
)
from viper.serialization import parse_yaml_bytes, serialize_document
from viper.stages import (
    BaseSpec,
    BuildSpec,
    DownloadSpec,
    EmbedSpec,
    EvaluateSpec,
    StageImplementationRef,
    TrainSpec,
)
from viper.storage import LocalArtifactStore

ACQUISITION_RUN_ID = "01ARZ3NDEKTSV4RRFFQ69G5FAC"
CANDIDATE_RUN_ID = "01ARZ3NDEKTSV4RRFFQ69G5FAD"
http_source = execution_http_source


def _stage_implementation(root: Path, stage: str) -> StageImplementationRef:
    """Identify one generated decorated stage by its exact bytes."""
    path = f"src/sample_project/stages/{stage}.py"
    raw = (root / path).read_bytes()
    return StageImplementationRef(
        path=path,
        symbol=stage,
        sha256=hashlib.sha256(raw).hexdigest(),
        bytes=len(raw),
    )


def _parameter_model(root: Path, symbol: str) -> ParameterModelRef:
    """Identify one class in the generated parameter module."""
    path = "src/sample_project/parameters.py"
    raw = (root / path).read_bytes()
    return ParameterModelRef(
        path=path,
        symbol=symbol,
        sha256=hashlib.sha256(raw).hexdigest(),
        bytes=len(raw),
    )


def _loader(root: Path, name: str = "bytes_file") -> ArtifactLoaderRef:
    """Identify one generated artifact loader by its exact bytes."""
    path = f"src/sample_project/artifact_loaders/{name}.py"
    raw = (root / path).read_bytes()
    return ArtifactLoaderRef(
        path=path,
        symbol="load",
        sha256=hashlib.sha256(raw).hexdigest(),
        bytes=len(raw),
    )


def _artifact(
    root: Path,
    path: str,
    role: DataRole,
    *,
    loader_name: str = "bytes_file",
) -> SingleFileArtifactSpec:
    """Declare one generated file artifact and its reconstruction function."""
    return SingleFileArtifactSpec(
        path=path,
        loader=_loader(root, loader_name),
        data_role=role,
    )


def _source(commit: str) -> GitSource:
    """Select one immutable source commit in the generated test repository."""
    return GitSource.model_validate({"repository": REPOSITORY, "commit": commit})


def _environment(commit: str) -> LocalEnvironmentSpec | GCEEnvironmentSpec:
    """Bind the active local or live GCE host to the generated project."""
    lockfile = GitFileRef.model_validate(
        {
            "repository": REPOSITORY,
            "commit": commit,
            "path": "pyproject.toml",
        }
    )
    if os.environ.get("VIPER_LIVE_GCE") == "1":
        return GCEEnvironmentSpec(
            provisioning=observe_gce_provisioning(),
            machine_type="g2-standard-12",
            compute=CPUComputeSpec(),
            lockfile=lockfile,
            python_environment=python_environment(),
        )
    return LocalEnvironmentSpec(
        lockfile=lockfile,
        python_environment=python_environment(),
    )


def _freeze(
    root: Path,
    *,
    run_id: str,
    experiment_id: str,
    seed: int,
    source_commit: str,
    stages: Mapping[str, BaseSpec],
    benchmark_id: str | None = None,
) -> Path:
    """Freeze and commit one complete plan assembled by this acceptance case."""
    draft_root = root / ".viper" / "drafts" / run_id
    draft_root.mkdir(parents=True)
    stage_drafts = []
    for stage_id, stage in stages.items():
        path = draft_root / f"{stage_id}.yaml"
        path.write_bytes(serialize_document(stage))
        stage_drafts.append(StageDraft(stage_id=stage_id, spec_source=path))
    frozen = freeze_run_plan(
        root,
        RunPlanDraft(
            run_id=run_id,
            experiment_id=experiment_id,
            variant_id="baseline",
            replicate_id="r1",
            benchmark_id=benchmark_id,
            seed=seed,
            source=_source(source_commit),
            environment=_environment(source_commit),
            reproducibility=reproducibility(),
            stages=tuple(stage_drafts),
            estimator=StageArtifactRef(
                stage_id="train",
                artifact_name=PARAMETERS,
            ),
        ),
    )
    run_git(root, "add", f"experiments/{experiment_id}/runs")
    run_git(root, "commit", "--quiet", "-m", f"freeze {experiment_id} plan")
    return frozen.files[-1]


def _pointer_ref(commit: str, path: str) -> ArtifactPointerRef:
    """Select one promoted pointer from the commit that published it."""
    return ArtifactPointerRef.model_validate(
        {"repository": REPOSITORY, "commit": commit, "path": path}
    )


def _child_environment(root: Path) -> dict[str, str]:
    """Expose generated source while rejecting bare ``python`` worker launches."""
    environment = os.environ.copy()
    existing_python_path = environment.get("PYTHONPATH")
    source_paths = os.pathsep.join((str(root / "src"), str(Path(__file__).parents[1])))
    environment["PYTHONPATH"] = (
        source_paths
        if existing_python_path is None
        else f"{source_paths}{os.pathsep}{existing_python_path}"
    )
    shadow_bin = root / ".viper" / "test-bin"
    shadow_bin.mkdir(parents=True, exist_ok=True)
    shadow_python = shadow_bin / "python"
    shadow_python.write_text("#!/bin/sh\nexit 97\n", encoding="utf-8")
    shadow_python.chmod(0o755)
    environment["PATH"] = os.pathsep.join(
        (str(shadow_bin), environment.get("PATH", ""))
    )
    return environment


def test_generated_project_uses_runner_owned_downloads(
    tmp_path: Path,
    http_source: tuple[str, int],
) -> None:
    """Run generated code through acquisition, training, and confirmation."""
    root = tmp_path / "generated"
    init(root, "sample_project")
    assert not (root / "src/sample_project/stages/download.py").exists()
    assert "DownloadParameters" not in (
        root / "src/sample_project/parameters.py"
    ).read_text(encoding="utf-8")
    run_git(root, "init", "--quiet")
    run_git(root, "config", "user.email", "viper@example.com")
    run_git(root, "config", "user.name", "VIPER Test")
    run_git(root, "remote", "add", "origin", REPOSITORY)
    host, port = http_source

    train_params = parameters.Train.model_validate({"epochs": 1})
    write_experiment_spec(
        root,
        ExperimentSpec(
            experiment_id="acquisition",
            factors=(),
            variant_ids=("baseline",),
            replicates=(ReplicateSpec(replicate_id="r1", seed=11),),
            metrics=(),
        ),
    )
    write_variant_spec(
        root,
        VariantSpec(
            experiment_id="acquisition",
            variant_id="baseline",
            levels={},
            stage_params=(
                TrainVariantStageParams(stage_id="train", params=train_params),
            ),
        ),
    )
    run_git(root, "add", ".")
    run_git(root, "commit", "--quiet", "-m", "generated acquisition source")
    acquisition_source_commit = run_git(root, "rev-parse", "HEAD")
    acquisition_root = f"experiments/acquisition/runs/baseline/{ACQUISITION_RUN_ID}"
    acquisition_download = DownloadSpec(
        inputs={
            name: http_request(
                url=f"http://{host}:{port}/prior",
                body=b"prior",
                version=f"{name}-v1",
            )
            for name in ("seed_training", "evaluation_dataset", "test_split")
        },
        http=builtin_http(),
        policy=http_policy(hosts=frozenset({host}), ports=frozenset({port})),
        artifacts={
            "seed_training": _artifact(
                root,
                f"{acquisition_root}/artifacts/datasets/starter/seed.bin",
                "training",
            ),
            "evaluation_dataset": _artifact(
                root,
                f"{acquisition_root}/artifacts/datasets/starter/evaluation.bin",
                "benchmark",
            ),
            "test_split": _artifact(
                root,
                f"{acquisition_root}/artifacts/datasets/starter/test_split.bin",
                "benchmark",
            ),
        },
    )
    acquisition_train = TrainSpec(
        implementation=_stage_implementation(root, "train"),
        parameter_model=_parameter_model(root, "TrainParameters"),
        inputs={
            "dataset": FutureInputRef(
                producer_stage_id="download",
                name="seed_training",
            )
        },
        params=train_params,
        artifacts={
            PARAMETERS: _artifact(
                root,
                f"{acquisition_root}/artifacts/models/starter/parameters.bin",
                "training",
            ),
            RESUME_STATE: _artifact(
                root,
                f"{acquisition_root}/artifacts/models/starter/resume_state.bin",
                "training",
                loader_name="resume_state",
            ),
        },
    )
    acquisition_plan = _freeze(
        root,
        run_id=ACQUISITION_RUN_ID,
        experiment_id="acquisition",
        seed=11,
        source_commit=acquisition_source_commit,
        stages={"download": acquisition_download, "train": acquisition_train},
    )
    child_environment = _child_environment(root)
    acquisition_process = subprocess.run(
        (
            sys.executable,
            "-m",
            "viper.cli",
            "--json",
            "run",
            str(acquisition_plan),
            "--root",
            str(root),
        ),
        cwd=root,
        env=child_environment,
        check=False,
        capture_output=True,
    )
    assert acquisition_process.returncode == 0, acquisition_process.stderr.decode()
    acquisition_result_path = root / acquisition_root / "resolved.yaml"
    acquisition_result = ResolvedRun.model_validate(
        parse_yaml_bytes(acquisition_result_path.read_bytes())
    )
    assert acquisition_result.status == "succeeded"

    store = LocalArtifactStore(root)
    resolved_run_raw = acquisition_result_path.read_bytes()
    resolved_run_file = store.resolved_files(
        {acquisition_result_path.relative_to(root).as_posix(): resolved_run_raw}
    )[0]
    producer = ResolvedRunRef.model_validate(resolved_run_file.model_dump())
    evaluation_pointer_path = "inputs/datasets/starter/evaluation.pointer.yaml"
    split_pointer_path = "inputs/benchmarks/starter/test_split.pointer.yaml"
    pointer_documents = {
        evaluation_pointer_path: ArtifactPointer(
            run=producer,
            artifact=StageArtifactRef(
                stage_id="download",
                artifact_name="evaluation_dataset",
            ),
        ),
        split_pointer_path: ArtifactPointer(
            run=producer,
            artifact=StageArtifactRef(
                stage_id="download",
                artifact_name="test_split",
            ),
        ),
    }
    for path, pointer in pointer_documents.items():
        target = root / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(serialize_document(pointer))
    run_git(root, "add", *pointer_documents)
    run_git(root, "commit", "--quiet", "-m", "promote benchmark inputs")
    pointer_commit = run_git(root, "rev-parse", "HEAD")
    evaluation_pointer = _pointer_ref(pointer_commit, evaluation_pointer_path)
    split_pointer = _pointer_ref(pointer_commit, split_pointer_path)

    metric_path = "src/sample_project/metrics/evaluation.py"
    metric_raw = (root / metric_path).read_bytes()
    metric = MetricSpec(
        metric_id="prediction_bytes",
        kind="evaluation",
        implementation=MetricImplementationRef(
            path=metric_path,
            symbol="prediction_bytes",
            sha256=hashlib.sha256(metric_raw).hexdigest(),
            bytes=len(metric_raw),
        ),
        params=parameters.Metric(),
        mode="recompute",
        dependencies=(
            MetricDependency(
                source="artifact",
                name=PREDICTIONS,
                required_data_role="benchmark",
            ),
        ),
        comparator=FloatComparator(),
    )
    build_params = parameters.Build.model_validate({"delimiter": ","})
    embed_params = parameters.Embed.model_validate({"dimensions": 2})
    evaluate_params = parameters.Evaluate.model_validate({"label": "baseline"})
    write_experiment_spec(
        root,
        ExperimentSpec(
            experiment_id="starter",
            factors=(),
            variant_ids=("baseline",),
            replicates=(ReplicateSpec(replicate_id="r1", seed=17),),
            metrics=(metric,),
        ),
    )
    write_variant_spec(
        root,
        VariantSpec(
            experiment_id="starter",
            variant_id="baseline",
            levels={},
            stage_params=(
                BuildVariantStageParams(stage_id="build", params=build_params),
                EmbedVariantStageParams(stage_id="embed", params=embed_params),
                TrainVariantStageParams(stage_id="train", params=train_params),
                EvaluateVariantStageParams(
                    stage_id="evaluate",
                    params=evaluate_params,
                ),
            ),
        ),
    )
    benchmark_path = write_benchmark_spec(
        root,
        BenchmarkSpec(
            benchmark_id="starter",
            evaluation_id="starter_eval",
            evaluation_dataset=evaluation_pointer,
            splits={"test_split": split_pointer},
            metrics=(
                MetricCriterion(
                    metric_id="prediction_bytes",
                    comparison="ge",
                    threshold=1.0,
                ),
            ),
        ),
    )
    run_git(root, "add", "experiments/starter", "benchmarks/starter.spec.yaml")
    run_git(root, "commit", "--quiet", "-m", "define benchmark candidate")
    candidate_source_commit = run_git(root, "rev-parse", "HEAD")
    candidate_root = f"experiments/starter/runs/baseline/{CANDIDATE_RUN_ID}"
    candidate_download = DownloadSpec(
        inputs={
            "dataset": http_request(
                url=f"http://{host}:{port}/prior",
                body=b"prior",
                version="training-v1",
            )
        },
        http=builtin_http(),
        policy=http_policy(hosts=frozenset({host}), ports=frozenset({port})),
        artifacts={
            "dataset": _artifact(
                root,
                f"{candidate_root}/artifacts/datasets/starter/dataset.bin",
                "training",
            )
        },
    )
    candidate_build = BuildSpec(
        implementation=_stage_implementation(root, "build"),
        parameter_model=_parameter_model(root, "BuildParameters"),
        inputs={
            "dataset": FutureInputRef(
                producer_stage_id="download",
                name="dataset",
            )
        },
        params=build_params,
        artifacts={
            "prior": _artifact(
                root,
                f"{candidate_root}/artifacts/priors/starter/prior.bin",
                "training",
            )
        },
    )
    candidate_embed = EmbedSpec(
        implementation=_stage_implementation(root, "embed"),
        parameter_model=_parameter_model(root, "EmbedParameters"),
        inputs={
            "prior": FutureInputRef(
                producer_stage_id="build",
                name="prior",
            )
        },
        params=embed_params,
        artifacts={
            "embedding": _artifact(
                root,
                f"{candidate_root}/artifacts/models/starter/embedding.bin",
                "training",
            )
        },
    )
    candidate_train = TrainSpec(
        implementation=_stage_implementation(root, "train"),
        parameter_model=_parameter_model(root, "TrainParameters"),
        inputs={
            "embedding": FutureInputRef(
                producer_stage_id="embed",
                name="embedding",
            )
        },
        params=train_params,
        artifacts={
            PARAMETERS: _artifact(
                root,
                f"{candidate_root}/artifacts/models/starter/parameters.bin",
                "training",
            ),
            RESUME_STATE: _artifact(
                root,
                f"{candidate_root}/artifacts/models/starter/resume_state.bin",
                "training",
                loader_name="resume_state",
            ),
        },
    )
    candidate_evaluate = EvaluateSpec(
        implementation=_stage_implementation(root, "evaluate"),
        parameter_model=_parameter_model(root, "EvaluateParameters"),
        evaluation_id="starter_eval",
        metric_ids=("prediction_bytes",),
        split_inputs=("test_split",),
        inputs={
            PARAMETERS: FutureInputRef(
                producer_stage_id="train",
                name=PARAMETERS,
            ),
            "evaluation_dataset": StoredInputRef(
                pointer=evaluation_pointer,
                path="inputs/datasets/starter/evaluation.bin",
                data_role="benchmark",
            ),
            "test_split": StoredInputRef(
                pointer=split_pointer,
                path="inputs/benchmarks/starter/test_split.bin",
                data_role="benchmark",
            ),
        },
        params=evaluate_params,
        artifacts={
            PREDICTIONS: _artifact(
                root,
                (
                    f"{candidate_root}/artifacts/evaluations/"
                    "starter_eval/predictions.bin"
                ),
                "benchmark",
            )
        },
    )
    candidate_plan = _freeze(
        root,
        run_id=CANDIDATE_RUN_ID,
        experiment_id="starter",
        seed=17,
        source_commit=candidate_source_commit,
        benchmark_id="starter",
        stages={
            "download": candidate_download,
            "build": candidate_build,
            "embed": candidate_embed,
            "train": candidate_train,
            "evaluate": candidate_evaluate,
        },
    )
    subprocess.run(
        (
            sys.executable,
            "train.py",
            "--run",
            str(candidate_plan),
            "--stage",
            "train",
            "--root",
            str(root),
        ),
        cwd=root,
        env=child_environment,
        check=True,
        capture_output=True,
    )
    candidate_result_path = root / candidate_root / "resolved.yaml"
    candidate_result = ResolvedRun.model_validate(
        parse_yaml_bytes(candidate_result_path.read_bytes())
    )
    subprocess.run(
        (
            sys.executable,
            "-m",
            "viper.cli",
            "--json",
            "execute-benchmark",
            str(candidate_result_path),
            str(benchmark_path),
            "--root",
            str(root),
        ),
        cwd=root,
        env=child_environment,
        check=True,
        capture_output=True,
    )
    benchmark_result = BenchmarkResult.model_validate(
        parse_yaml_bytes(
            (candidate_result_path.parent / "benchmark.result.yaml").read_bytes()
        )
    )

    assert candidate_result.status == "succeeded"
    assert benchmark_result.status == "passed"
    assert len(benchmark_result.artifacts) == 2
    assert len(benchmark_result.metrics) == 1
